import { getTranslations, unstable_setRequestLocale } from 'next-intl/server';

import { Footer } from '@/templates/Footer';
import { Navbar } from '@/templates/Navbar';
import { Section } from '@/features/landing/Section';

export async function generateMetadata(props: { params: { locale: string } }) {
  const t = await getTranslations({
    locale: props.params.locale,
    namespace: 'Terms',
  });

  return {
    title: t('meta_title'),
    description: t('meta_description'),
  };
}

const TermsPage = (props: { params: { locale: string } }) => {
  unstable_setRequestLocale(props.params.locale);

  return (
    <>
      <Navbar />
      
      <Section className="py-36">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-4xl font-bold tracking-tight mb-6">
            Terms of Service
          </h1>
          <p className="text-lg text-muted-foreground mb-8">
            Last updated: September 4, 2025
          </p>
          
          <div className="prose prose-lg max-w-none">
            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing or using Morning AI's services, you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, please do not use our services.
            </p>

            <h2>2. Description of Service</h2>
            <p>
              Morning AI provides an intelligent design platform that combines AI-powered tools with design systems to help teams create products faster. Our services include design tools, component libraries, AI assistance, and collaboration features.
            </p>

            <h2>3. User Accounts</h2>
            <h3>3.1 Account Creation</h3>
            <p>To use certain features, you must create an account and provide accurate information. You are responsible for:</p>
            <ul>
              <li>Maintaining the confidentiality of your account credentials</li>
              <li>All activities that occur under your account</li>
              <li>Notifying us immediately of any unauthorized use</li>
            </ul>

            <h3>3.2 Account Eligibility</h3>
            <p>You must be at least 18 years old to create an account. By creating an account, you represent that you meet this requirement.</p>

            <h2>4. Acceptable Use</h2>
            <p>You agree not to use our services to:</p>
            <ul>
              <li>Violate any applicable laws or regulations</li>
              <li>Infringe on intellectual property rights</li>
              <li>Upload malicious code or harmful content</li>
              <li>Attempt to gain unauthorized access to our systems</li>
              <li>Interfere with or disrupt our services</li>
              <li>Use our services for competitive analysis or reverse engineering</li>
            </ul>

            <h2>5. Intellectual Property</h2>
            <h3>5.1 Our Content</h3>
            <p>
              Morning AI retains all rights to our platform, software, and proprietary content. You may not copy, modify, or distribute our intellectual property without permission.
            </p>

            <h3>5.2 Your Content</h3>
            <p>
              You retain ownership of the content you create using our services. By using our services, you grant us a limited license to process, store, and display your content as necessary to provide our services.
            </p>

            <h3>5.3 AI-Generated Content</h3>
            <p>
              Content generated by our AI tools is provided "as is." You are responsible for reviewing and ensuring the appropriateness of AI-generated content before use.
            </p>

            <h2>6. Privacy and Data Protection</h2>
            <p>
              Your privacy is important to us. Our collection and use of your information is governed by our Privacy Policy, which is incorporated into these Terms by reference.
            </p>

            <h2>7. Subscription and Payment</h2>
            <h3>7.1 Subscription Plans</h3>
            <p>We offer various subscription plans with different features and usage limits. Subscription fees are billed in advance and are non-refundable except as required by law.</p>

            <h3>7.2 Payment Terms</h3>
            <ul>
              <li>Payments are processed through secure third-party providers</li>
              <li>You authorize us to charge your payment method for applicable fees</li>
              <li>Subscription automatically renews unless cancelled</li>
              <li>Price changes will be communicated with 30 days notice</li>
            </ul>

            <h3>7.3 Cancellation</h3>
            <p>You may cancel your subscription at any time. Cancellation takes effect at the end of your current billing period.</p>

            <h2>8. Service Availability</h2>
            <p>
              We strive to maintain high service availability but cannot guarantee uninterrupted access. We may temporarily suspend services for maintenance, updates, or other operational reasons.
            </p>

            <h2>9. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Morning AI shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of our services.
            </p>

            <h2>10. Indemnification</h2>
            <p>
              You agree to indemnify and hold Morning AI harmless from any claims, damages, or expenses arising from your use of our services or violation of these Terms.
            </p>

            <h2>11. Termination</h2>
            <p>
              We may terminate or suspend your account immediately if you violate these Terms. Upon termination, your right to use our services ceases, and we may delete your account and data.
            </p>

            <h2>12. Dispute Resolution</h2>
            <h3>12.1 Governing Law</h3>
            <p>These Terms are governed by the laws of the State of California, without regard to conflict of law principles.</p>

            <h3>12.2 Arbitration</h3>
            <p>
              Any disputes arising from these Terms will be resolved through binding arbitration in accordance with the rules of the American Arbitration Association.
            </p>

            <h2>13. Changes to Terms</h2>
            <p>
              We may modify these Terms at any time. Material changes will be communicated via email or through our platform. Continued use of our services after changes constitutes acceptance of the new Terms.
            </p>

            <h2>14. Severability</h2>
            <p>
              If any provision of these Terms is found to be unenforceable, the remaining provisions will continue in full force and effect.
            </p>

            <h2>15. Contact Information</h2>
            <p>
              For questions about these Terms, please contact us at:
            </p>
            <ul>
              <li>Email: legal@morningai.me</li>
              <li>Address: 123 Innovation Drive, San Francisco, CA 94105</li>
            </ul>

            <h2>16. Entire Agreement</h2>
            <p>
              These Terms, together with our Privacy Policy, constitute the entire agreement between you and Morning AI regarding the use of our services.
            </p>
          </div>
        </div>
      </Section>

      <Footer />
    </>
  );
};

export default TermsPage;

