#
# Your Crowdin credentials
#
# No need modify CROWDIN_PROJECT_ID and CROWDIN_PERSONAL_TOKEN, you can set them in GitHub Actions secrets
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .
base_url: 'https://api.crowdin.com' # https://{organization-name}.crowdin.com for Crowdin Enterprise

#
# Choose file structure in Crowdin
# e.g. true or false
#
preserve_hierarchy: true

#
# Files configuration
# English is now the source of truth for all translations
#
files:
  - source: /src/locales/en.json

    #
    # Where translations will be placed
    # Maps to specific language codes for Traditional Chinese and Simplified Chinese
    #
    translation: '/src/locales/%locale_with_underscore%.json'

    #
    # File type
    # e.g. "json"
    #
    type: json

    #
    # Language mapping for correct file naming
    #
    languages_mapping:
      locale_with_underscore:
        zh-TW: zh-TW
        zh-CN: zh-CN
